apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        app: voting-app
        name: db
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
         - mountPath: "/var/lib/postgresql/data"
           name: "db-data"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
      volumes:
        - name: db-data
          emptyDir: {}      
  replicas: 2