apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
    app: voting-app
spec:
  type: ClusterIP
  selector:
    app: voting-app
    name: db
  ports:
  - port: 5432
    targetPort: 5432
