apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: voting-app
spec:
  selector:
    app: voting-app
    name: db-pod
  ports:
  - port: 5432
    targetPort: 5432
