apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: voting-app
spec:
  type: ClusterIP
  selector:
    app: redis-pod
  ports:
  - port: 6379
    targetPort: 6379
