apiVersion: v1
kind: Service
metadata:
  name: results-service
  labels:
    name: results-service
    app: voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    name: results-app-pod
    app: voting-app