apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: results-app-pod
  template:
    metadata:
      name: results-app-pod
      labels:
        app: voting-app
        name: results-app-pod
    spec:
      containers:
      - name: results-app
        image: examplevotingapp_result:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
