apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: results-app-pod
  template:
    metadata:
      name: results-app-pod
      labels:
        app: results-app-pod
        name: results-app-pod
    spec:
      containers:
      - name: results-app
        image: kodekloud/examplevotingapp_result:before
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
