apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-app-pod
  template:
    metadata:
      name: voting-app-pod
      labels:
        app: voting-app
        name: voting-app-pod
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
