apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: voting-app
spec:
  type: NodePort
  selector:
    app: voting-app
    name: voting-app-pod
  ports:
  - port: 5000
    targetPort: 80
    nodePort: 31000
