apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: voting-app
spec:
  type: NodePort
  selector:
    app: voting-app
    name: voting-app-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
