apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker-pod
  template:
    metadata:
      labels:
        app: voting-app
        name: worker-pod
    spec:
      containers:
      - name: worker
        image: kodekloud/examplevotingapp_worker:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
